name: Release

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to release'
        required: true
        default: 'main'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.branch }}

      # Setup Node and pnpm (specify pnpm version)
      - uses: pnpm/action-setup@v4
        with:
          version: 'latest'

      - uses: actions/setup-node@v4
        with:
          node-version: 'latest'
          cache: 'pnpm'

      # Install dependencies
      - name: Install dependencies
        run: pnpm install

      # Build and zip the extensions
      - name: Zip extensions
        run: |
          pnpm zip
          pnpm zip:firefox

      # List output directory for debugging
      - name: List output directory
        run: ls -la ./.output/

      # Find and set Chrome asset path dynamically
      - name: Set Chrome asset path
        id: set_chrome_asset
        run: echo "chrome_asset=$(ls ./.output/*-chrome.zip)" >> $GITHUB_ENV

      # Debug the Chrome asset path
      - name: Debug Chrome asset path
        run: echo "Chrome asset path: ${{ env.chrome_asset }}"

      # Create GitHub Release
      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        with:
          tag_name: "v${{ github.run_number }}"
          release_name: "Release ${{ github.run_number }} for ${{ github.event.inputs.branch }}"
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Upload Chrome extension zip
      - name: Upload Chrome zip to release
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ${{ env.chrome_asset }}
          asset_name: chrome-extension-v${{ github.run_number }}.zip
          asset_content_type: application/zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Ensure the token is set
